[build]
  command = "npm run build"
  publish = "dist"
  functions = "functions"
  
[build.environment]
  NODE_VERSION = "18"
  VITE_API_URL = "/.netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' 'unsafe-eval' data: *.netlify.app netlify.app *.instagram.com *.rapidapi.com *.openai.com fonts.googleapis.com fonts.gstatic.com cdn.jsdelivr.net;"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block" 